### ISSUE TITLE
Hi amazing desktop

### ISSUE THREAD

**Issue by andresparrab** [nawfalmrouyan/hyprland#1]
I was wondering if you could m,aybe do a how to viodeo or explain here how do you do for intall arch ins this.

I have installed archo linux barebone and then added hyperland. but then there was no filemanager or something that control the cpu. because is running at 80 degrees all the time. and of course i dont havce volume control . 
in you package list i see only the things for the UI deskop. but if i would liek to have something that is ready to use like example endeavour os, you jsut install and all things behind are taking care off.

sorry im just new to wayland desktop environment. but i dont see come with cpu controll and file manager etc.

i woiuld apreciate any help to get hyperland up and running from, a base-level arch install. 
thank you in advance

**Comment by nawfalmrouyan** [comment]
I would suggest for you to install other complete Desktop Environments like KDE or GNOME. They come with lots of utility applications like File Manager, etc.

Then you can use them in Hyprland. Once you're familiar with all those applications, you can pick and choose which you would like to use and uninstall others.
