### ISSUE TITLE
Invalid dispatcher

### ISSUE THREAD

**Issue by kurniawan2805** [nawfalmrouyan/hyprland#2]
Hi, I am trying to install your configuration but find error:
```
Config error at line 249 (~/.config/hypr/hyprland.conf): Invalid dispatcher, requested "moveintogroup" does not exist.
```
What this means?

I am starting by install arcolinuxB hyprland then copy all of your hyprland folder.
Thanks

**Comment by nawfalmrouyan** [comment]
In case you're still having issues, please use the git version of Hyprland.

For me, I'm using hyprland-nvidia-git AUR.
